# Generated by Django 4.1 on 2022-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='equals_sign',
            field=models.BooleanField(default=False),
        ),
    ]
